import {initialState, elapsed, loadState, saveState, exportState} from './core.js';

const root=document.querySelector('#root'); let state=loadState(); let page='today'; let ratingId=null; let simulation=0;
const repertoire=[['Tosca','Köln · New material','TODAY · HIGH PRIORITY'],['Debussy Cello Sonata','Buchet · Newer work','TODAY · HIGH FREQUENCY'],['Haydn D major Concerto','Köln · Core','TODAY'],['Schumann Cello Concerto','Köln · Core','TODAY'],['Don Juan','Köln · Orchestral','TODAY'],['Bach Suite No. 2','Buchet · Reactivation','TODAY'],['Wagner Walküre','Köln · Orchestral','DO NOT PRACTICE · review in 48h'],['Ligeti Solo Sonata','Buchet · Reactivation','DO NOT PRACTICE · consolidating']];
const metrics=['Intonation','Left-hand frame','Finger clarity','Left-hand freedom','Right-hand sound','Right-hand articulation','Musical freedom'];
const all=()=>state.sessions.flatMap(s=>s.tasks); const find=id=>all().find(t=>t.id===id); const clock=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){saveState(state)}
function header(){return `<header><div class="brand">CELLO PRACTICE LAB</div><button class="ghost" data-action="simulate">AUDITION SIMULATION</button></header>`}
function nav(){return `<nav>${['today','practice','repertoire','progress','settings'].map(p=>`<button data-page="${p}" class="${page===p?'on':''}"><i>${{today:'⌂',practice:'◷',repertoire:'≡',progress:'↗',settings:'·'}[p]}</i>${p}</button>`).join('')}</nav>`}
function taskCard(t){return `<article class="task ${t.status}"><div class="taskTop"><div>${t.tags.map(x=>`<span class="tag">${x}</span>`).join('')}<h3>${t.title}</h3><p>${t.subtitle}</p></div><div class="timer" data-timer="${t.id}">${clock(elapsed(t))}<small>/ ${t.minutes}:00</small></div></div><div class="actions"><button class="primary" data-action="${t.status==='active'?'pause':'start'}" data-id="${t.id}">${t.status==='active'?'PAUSE':'START'}</button><button data-action="complete" data-id="${t.id}">COMPLETE</button><button data-action="skip" data-id="${t.id}">SKIP</button></div></article>`}
function today(){const actual=all().filter(t=>!t.tags.includes('BREAK')).reduce((a,t)=>a+elapsed(t),0), performance=all().filter(t=>t.tags.includes('PERFORMANCE')||t.tags.includes('FIRST TAKE')).reduce((a,t)=>a+elapsed(t),0),active=find(state.activeTaskId);return `<section class="hero"><div><span>TODAY · DAY 1</span><h1>Build the playing<br>that survives the first take.</h1><p>Post-MDR reset · Foundation before volume</p></div><div class="date">01<br><small>OCT 2026</small></div></section><section class="stats">${[['PRACTICE TARGET','180 min'],['ACTUAL PRACTICE',`${Math.floor(actual/60)} min`],['PERFORMANCE TEMPO',`${Math.floor(performance/60)} min`],['CURRENT BLOCK',active?.title||'Ready']].map(x=>`<div><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</section><p class="sectionLabel">DAY 1 · 3H–3H15 ACTUAL PRACTICE</p>${state.sessions.map((s,i)=>`<section class="session"><div class="sessionTitle"><span>${s.label}</span><small>${s.kind==='practice'?'40 MIN':s.kind==='break'?'RECOVERY':'CHOOSE ONE'}</small></div>${s.tasks.map(taskCard).join('')}${i===2?'<div class="longBreak"><b>LARGE BREAK</b><span>Take the time you need. Return recovered, not scheduled.</span></div>':''}</section>`).join('')}`}
const pageHead=(title,sub)=>`<section class="pageHead"><span>CELLO PRACTICE LAB</span><h1>${title}</h1><p>${sub}</p></section>`;
function practice(){return pageHead('Practice methods','Acquire → transfer → consolidate → retrieve')+`<div class="guide"><h3>Performance-tempo exit</h3><p>Slow repair is not the endpoint. Move through medium → 90% → 100%. If completely free, touch 103–105% briefly, then return to 100%.</p><h3>Minimum effective pressure</h3><p>Explore heavy pressure, release until tone destabilizes, then add only a little back. 快 ≠ 紧 · 准 ≠ 按重 · 落下就走.</p><h3>Speed endurance</h3><p>20–40 sec at tempo → 20–30 sec recovery. Track where tension begins to accumulate.</p><h3>Right-hand contact</h3><p>Contact → articulation → freedom. Core is not pressure.</p></div><div class="safety"><b>LOAD PROTECTION</b><p>Pain, numbness, tingling, persistent weakness, or clearly worsening tension?</p><strong>Stop / reduce load. Do not push through pain.</strong><small>This app does not provide medical diagnosis.</small></div>`}
function rep(){return pageHead('Repertoire','Spacing is part of practice')+`<div class="repList">${repertoire.map((x,i)=>`<article><div><small>${x[1]}</small><h3>${x[0]}</h3><p>Last practiced · ${i<6?'Today':'2 days ago'}　 Last First Take · ${i%3?'A':'B'}</p></div><strong class="${x[2].includes('DO NOT')?'rest':''}">${x[2]}</strong></article>`).join('')}</div>`}
function progress(){const rates=['A','B','C'].map(g=>state.history.filter(x=>x.grade===g).length),avg=k=>state.history.length?(state.history.reduce((a,h)=>a+(k==='tension'?h.tension:h.ratings[k]||0),0)/state.history.length).toFixed(1):'—';return pageHead('Progress','Useful signals, never streaks')+`<section class="stats progress">${[['FIRST TAKE A / B / C',rates.join(' / ')],['AVG LEFT TENSION',avg('tension')]].map(x=>`<div><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</section><div class="trend">${['Intonation','Left-hand frame','Finger clarity','Right-hand sound'].map(x=>`<div><span>${x}</span><b>${avg(x)} / 5</b><i style="width:${state.history.length?Number(avg(x))*20:0}%"></i></div>`).join('')}</div>`}
function settings(){return pageHead('Settings','Your data stays on this device')+`<div class="settings"><button data-action="export">EXPORT JSON <span>Download a portable backup</span></button><button data-action="import">IMPORT JSON <span>Restore a previous backup</span></button><input id="import-file" hidden type="file" accept="application/json"><button class="danger" data-action="reset">RESET DAY 1 <span>Erase progress on this device</span></button></div><div class="guide"><h3>Install on iPhone</h3><p>Open in Safari, tap Share, then “Add to Home Screen.” Timers catch up after refresh, lock, or switching apps.</p></div>`}
function rating(){const t=find(ratingId);return !t?'':`<div class="modal"><form class="sheet" id="rating"><button type="button" class="x" data-action="close">×</button><span>QUICK REVIEW</span><h2>${t.title}</h2><label>FIRST TAKE</label><div class="grades">${['A','B','C'].map(g=>`<label><input type="radio" name="grade" value="${g}" ${g==='B'?'checked':''}><b>${g}</b><small>${g==='A'?'Acceptable':g==='B'?'Usable / risk':'Repair needed'}</small></label>`).join('')}</div>${metrics.map(m=>`<div class="metric"><span>${m}</span><select name="${m}">${[1,2,3,4,5].map(n=>`<option ${n===3?'selected':''}>${n}</option>`).join('')}</select></div>`).join('')}<label>LEFT FOREARM TENSION</label><input name="tension" type="range" min="0" max="10" value="3"><textarea name="note" placeholder="Where did tension start? Notes…"></textarea><button class="primary full">SAVE REVIEW</button></form></div>`}
function sim(){return simulation<0?'':`<div class="modal shade"><div class="simulation"><button class="x" data-action="close-sim">×</button><span>AUDITION MODE</span><h2>${simulation?`Mental preparation · ${simulation}s`:'Begin. Performance tempo.'}</h2><p>${simulation?'Do not touch the passage. Hear the opening internally.':'框架——走——呼吸。'}</p><div class="quote">“不追厅，听琴。厅越干，手越松。”</div></div></div>`}
function render(){root.innerHTML=`<div class="app">${header()}<main>${({today,practice,repertoire:rep,progress,settings})[page]()}</main>${nav()}${rating()}${simulation>=0?sim():''}</div>`}
function pause(t){t.actualSeconds=elapsed(t);t.timerStartedAt=null;t.status='paused';state.activeTaskId=null}
root.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-page]');if(!b)return;if(b.dataset.page){page=b.dataset.page;render();return}const t=find(b.dataset.id);if(b.dataset.action==='start'){const active=find(state.activeTaskId);if(active&&active!==t)pause(active);t.status='active';t.timerStartedAt=Date.now();state.activeTaskId=t.id}if(b.dataset.action==='pause')pause(t);if(['complete','skip'].includes(b.dataset.action)){t.actualSeconds=elapsed(t);t.timerStartedAt=null;t.status=b.dataset.action==='complete'?'complete':'skipped';state.activeTaskId=null;if(b.dataset.action==='complete'&&!t.tags.includes('BREAK'))ratingId=t.id}if(b.dataset.action==='close')ratingId=null;if(b.dataset.action==='simulate'){simulation=15}if(b.dataset.action==='close-sim')simulation=-1;if(b.dataset.action==='export'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([exportState(state)],{type:'application/json'}));a.download=`cello-practice-${state.date}.json`;a.click()}if(b.dataset.action==='import')document.querySelector('#import-file').click();if(b.dataset.action==='reset'&&confirm('Reset all local data?'))state=initialState();persist();render()});
root.addEventListener('submit',e=>{if(e.target.id!=='rating')return;e.preventDefault();const d=new FormData(e.target), ratings=Object.fromEntries(metrics.map(m=>[m,Number(d.get(m))]));const t=find(ratingId);t.grade=d.get('grade');t.ratings=ratings;t.tensionStart=d.get('note');state.history.push({date:state.date,task:t.title,grade:t.grade,ratings,tension:Number(d.get('tension'))});ratingId=null;persist();render()});
root.addEventListener('change',e=>{if(e.target.id!=='import-file')return;const reader=new FileReader();reader.onload=()=>{try{state=JSON.parse(reader.result);persist();render()}catch{alert('This backup could not be read.')}};reader.readAsText(e.target.files[0])});
setInterval(()=>{document.querySelectorAll('[data-timer]').forEach(n=>{const t=find(n.dataset.timer);n.firstChild.textContent=clock(elapsed(t))});if(simulation>0){simulation--;render()}},1000);
simulation=-1;render();
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
