import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {initialState,repertoire} from './data';
import {elapsed,exportState,loadState,saveState} from './storage';
import type {AppState,Grade,Task} from './types';
import './styles.css';

type Page='today'|'practice'|'repertoire'|'progress'|'settings';
const metrics=['Intonation','Left-hand frame','Finger clarity','Left-hand freedom','Right-hand sound','Right-hand articulation','Musical freedom'];
const clock=(s:number)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;

function App(){
 const [state,setState]=useState(loadState); const [page,setPage]=useState<Page>('today'); const [now,setNow]=useState(Date.now()); const [rating,setRating]=useState<Task|null>(null); const [simulate,setSimulate]=useState(false); const [prep,setPrep]=useState(15); const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{saveState(state)},[state]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(!simulate)return;const id=setInterval(()=>setPrep(p=>p<=1?(clearInterval(id),0):p-1),1000);return()=>clearInterval(id)},[simulate]);
 const all=state.sessions.flatMap(s=>s.tasks); const active=all.find(t=>t.id===state.activeTaskId); const actual=all.filter(t=>!t.tags.includes('BREAK')).reduce((a,t)=>a+elapsed(t,now),0); const performance=all.filter(t=>t.tags.includes('PERFORMANCE')||t.tags.includes('FIRST TAKE')).reduce((a,t)=>a+elapsed(t,now),0);
 function mutate(id:string,fn:(t:Task)=>Task){setState(s=>({...s,sessions:s.sessions.map(x=>({...x,tasks:x.tasks.map(t=>t.id===id?fn(t):t)}))}))}
 function start(t:Task){if(active&&active.id!==t.id) pause(active); mutate(t.id,x=>({...x,status:'active',timerStartedAt:Date.now()}));setState(s=>({...s,activeTaskId:t.id}))}
 function pause(t:Task){mutate(t.id,x=>({...x,status:'paused',actualSeconds:elapsed(x),timerStartedAt:undefined}));setState(s=>({...s,activeTaskId:undefined}))}
 function finish(t:Task,status:'complete'|'skipped'){mutate(t.id,x=>({...x,status,actualSeconds:elapsed(x),timerStartedAt:undefined}));setState(s=>({...s,activeTaskId:undefined}));if(status==='complete'&&!t.tags.includes('BREAK'))setRating({...t,actualSeconds:elapsed(t)})}
 const target=180;
 return <div className="app">
  <header><div className="brand">CELLO PRACTICE LAB</div><button className="ghost focus" onClick={()=>{setSimulate(true);setPrep(15)}}>AUDITION SIMULATION</button></header>
  <main>
   {page==='today'&&<><section className="hero"><div><span>TODAY · DAY 1</span><h1>Build the playing<br/>that survives the first take.</h1><p>Post-MDR reset · Foundation before volume</p></div><div className="date">01<br/><small>OCT 2026</small></div></section>
    <section className="stats"><Stat label="PRACTICE TARGET" value={`${target} min`}/><Stat label="ACTUAL PRACTICE" value={`${Math.floor(actual/60)} min`}/><Stat label="PERFORMANCE TEMPO" value={`${Math.floor(performance/60)} min`}/><Stat label="CURRENT BLOCK" value={active?.title||'Ready'}/></section>
    <p className="sectionLabel">DAY 1 · 3H–3H15 ACTUAL PRACTICE</p>
    {state.sessions.map((s,i)=><section className="session" key={s.id}><div className="sessionTitle"><span>{s.label}</span><small>{s.kind==='practice'?'40 MIN':s.kind==='break'?'RECOVERY':'CHOOSE ONE'}</small></div>{s.tasks.map(t=><TaskCard key={t.id} task={t} now={now} onStart={start} onPause={pause} onFinish={finish}/>) }{i===2&&<div className="longBreak"><b>LARGE BREAK</b><span>Take the time you need. Return recovered, not scheduled.</span></div>}</section>)}
   </>}
   {page==='practice'&&<PracticeGuide/>}
   {page==='repertoire'&&<Repertoire/>}
   {page==='progress'&&<Progress state={state} actual={actual} performance={performance}/>} 
   {page==='settings'&&<Settings state={state} setState={setState} file={file}/>} 
  </main>
  <nav>{(['today','practice','repertoire','progress','settings'] as Page[]).map(p=><button className={page===p?'on':''} onClick={()=>setPage(p)} key={p}><i>{p==='today'?'⌂':p==='practice'?'◷':p==='repertoire'?'≡':p==='progress'?'↗':'·'}</i>{p}</button>)}</nav>
  {rating&&<Rating task={rating} close={()=>setRating(null)} save={(grade,ratings,tension,note)=>{mutate(rating.id,t=>({...t,grade,ratings,tensionStart:note}));setState(s=>({...s,firstTakes:s.firstTakes+1,history:[...s.history,{date:s.date,task:rating.title,grade,ratings,tension}]}));setRating(null)}}/>}
  {simulate&&<div className="modal shade"><div className="simulation"><button className="x" onClick={()=>setSimulate(false)}>×</button><span>AUDITION MODE</span><h2>{prep?`Mental preparation · ${prep}s`:'Begin. Performance tempo.'}</h2><p>{prep?'Do not touch the passage. Hear the opening internally.':'框架——走——呼吸。'}</p><div className="quote">“不追厅，听琴。厅越干，手越松。”</div>{!prep&&<button className="primary" onClick={()=>setSimulate(false)}>START FIRST TAKE</button>}</div></div>}
 </div>
}
function Stat({label,value}:{label:string,value:string}){return <div><small>{label}</small><strong>{value}</strong></div>}
function TaskCard({task,now,onStart,onPause,onFinish}:{task:Task;now:number;onStart:(t:Task)=>void;onPause:(t:Task)=>void;onFinish:(t:Task,s:'complete'|'skipped')=>void}){const sec=elapsed(task,now);return <article className={`task ${task.status}`}><div className="taskTop"><div>{task.tags.map(x=><span className="tag" key={x}>{x}</span>)}<h3>{task.title}</h3><p>{task.subtitle}</p></div><div className="timer">{clock(sec)}<small>/ {task.minutes}:00</small></div></div><div className="actions">{task.status!=='active'?<button className="primary" onClick={()=>onStart(task)}>START</button>:<button className="primary" onClick={()=>onPause(task)}>PAUSE</button>}<button onClick={()=>onFinish(task,'complete')}>COMPLETE</button><button onClick={()=>onFinish(task,'skipped')}>SKIP</button></div></article>}
function Rating({task,close,save}:{task:Task;close:()=>void;save:(g:Grade,r:Record<string,number>,t:number,n:string)=>void}){const [g,setG]=useState<Grade>('B');const [r,setR]=useState(Object.fromEntries(metrics.map(x=>[x,3])));const [t,setT]=useState(3);const [n,setN]=useState('');return <div className="modal"><div className="sheet"><button className="x" onClick={close}>×</button><span>QUICK REVIEW</span><h2>{task.title}</h2><label>FIRST TAKE</label><div className="grades">{(['A','B','C'] as Grade[]).map(x=><button className={g===x?'selected':''} onClick={()=>setG(x)} key={x}>{x}<small>{x==='A'?'Acceptable':x==='B'?'Usable / risk':'Repair needed'}</small></button>)}</div>{metrics.map(m=><div className="metric"><span>{m}</span><div>{[1,2,3,4,5].map(x=><button className={r[m]===x?'selected':''} onClick={()=>setR({...r,[m]:x})}>{x}</button>)}</div></div>)}<label>LEFT FOREARM TENSION · {t}/10</label><input type="range" min="0" max="10" value={t} onChange={e=>setT(+e.target.value)}/><textarea placeholder="Where did tension start? Notes…" value={n} onChange={e=>setN(e.target.value)}/><button className="primary full" onClick={()=>save(g,r,t,n)}>SAVE REVIEW</button></div></div>}
function PracticeGuide(){return <Page title="Practice methods" sub="Acquire → transfer → consolidate → retrieve"><div className="guide"><h3>Performance-tempo exit</h3><p>Slow repair is not the endpoint. Move through medium → 90% → 100%. If completely free, touch 103–105% briefly, then return to 100%.</p><h3>Minimum effective pressure</h3><p>Explore heavy pressure, release until tone destabilizes, then add only a little back. 快 ≠ 紧 · 准 ≠ 按重 · 落下就走.</p><h3>Speed endurance</h3><p>20–40 sec at tempo → 20–30 sec recovery. Track where tension begins to accumulate.</p><h3>Right-hand contact</h3><p>Contact → articulation → freedom. Near the bridge, balance contact point, bow speed, arm weight and hair/string contact. Core is not pressure.</p></div><div className="safety"><b>LOAD PROTECTION</b><p>Pain, numbness, tingling, persistent weakness, or clearly worsening tension?</p><strong>Stop / reduce load. Do not push through pain.</strong><small>This app does not provide medical diagnosis.</small></div></Page>}
function Repertoire(){return <Page title="Repertoire" sub="Spacing is part of practice"><div className="repList">{repertoire.map((x,i)=><article key={x[0]}><div><small>{x[1]}</small><h3>{x[0]}</h3><p>Last practiced · {i<6?'Today':'2 days ago'}　 Last First Take · {i%3===0?'B':'A'}</p></div><strong className={x[2].includes('DO NOT')?'rest':''}>{x[2]}</strong></article>)}</div></Page>}
function Progress({state,actual,performance}:{state:AppState;actual:number;performance:number}){const rates=['A','B','C'].map(g=>state.history.filter(x=>x.grade===g).length); const avg=(key:string)=>state.history.length?(state.history.reduce((a,h)=>a+(key==='tension'?h.tension:h.ratings[key]||0),0)/state.history.length).toFixed(1):'—';return <Page title="Progress" sub="Useful signals, never streaks"><section className="stats progress"><Stat label="WEEKLY PRACTICE" value={`${Math.floor(actual/60)} min`}/><Stat label="PERFORMANCE TEMPO" value={`${Math.floor(performance/60)} min`}/><Stat label="FIRST TAKE A / B / C" value={rates.join(' / ')}/><Stat label="AVG LEFT TENSION" value={avg('tension')}/></section><div className="trend">{['Intonation','Left-hand frame','Finger clarity','Right-hand sound'].map((x,i)=><div><span>{x}</span><b>{avg(x)} / 5</b><i style={{width:`${state.history.length?Number(avg(x))*20:0}%`}}/></div>)}</div><p className="empty">{state.history.length?'Trends update after every review.':'Complete a task and add a quick review to begin your baseline.'}</p></Page>}
function Settings({state,setState,file}:{state:AppState;setState:React.Dispatch<React.SetStateAction<AppState>>;file:React.RefObject<HTMLInputElement|null>}){function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([exportState(state)],{type:'application/json'}));a.download=`cello-practice-${state.date}.json`;a.click();URL.revokeObjectURL(a.href)}function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{setState(JSON.parse(String(reader.result)))}catch{alert('This backup could not be read.')}};reader.readAsText(f)}return <Page title="Settings" sub="Your data stays on this device"><div className="settings"><button onClick={download}>EXPORT JSON <span>Download a portable backup</span></button><button onClick={()=>file.current?.click()}>IMPORT JSON <span>Restore a previous backup</span></button><input hidden ref={file} type="file" accept="application/json" onChange={upload}/><button className="danger" onClick={()=>confirm('Reset all local data?')&&setState(initialState())}>RESET DAY 1 <span>Erase progress on this device</span></button></div><div className="guide"><h3>Install on iPhone</h3><p>Open in Safari, tap Share, then “Add to Home Screen.” Timers use timestamps, so an active session catches up after refresh, lock, or switching apps.</p><h3>Training week</h3><p>Default: six variable-load training days and one full recovery day. Do not attach recovery to a streak.</p></div></Page>}
function Page({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <><section className="pageHead"><span>CELLO PRACTICE LAB</span><h1>{title}</h1><p>{sub}</p></section>{children}</>}

createRoot(document.getElementById('root')!).render(<App/>);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));
